// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "blueHeart":return img`
....................
....................
....................
....................
....................
.......11...11......
......1881.1881.....
.....18988188881....
.....18988888881....
.....18888888881....
......188888c81.....
.......1888c81......
........18881.......
.........181........
..........1.........
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
